import type { Metadata } from "next";
import { Tajawal } from "next/font/google"; // Import the Poppins font
import "./globals.css";
import { AuthProvider } from "@/components/AuthContext";
import { Toaster } from "@/components/ui/toaster"
// Import Poppins with different weights if needed
import { TripProvider } from '@/context/TripContext';

const poppins = Tajawal({ subsets: ["latin"], weight: ["200","300", "400", "500", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={poppins.className} dir="rtl"> {/* Apply Poppins class */}
        <AuthProvider>
        <TripProvider>

          {children}
          <Toaster />
          </TripProvider>

        </AuthProvider>
      </body>
    </html>
  );
}
